default_stages: [commit, push]
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: detect-private-key
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: detect-aws-credentials
-   repo: https://gitlab.com/pycqa/flake8
    rev: '0c3b8045'
    hooks:
    -   id: flake8
        exclude: (tests|script)
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    -   id: mypy
        exclude: ^doc/
-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.2
    hooks:
    -    id: commitlint
         stages: [commit-msg]